name: hydro-all
channels:
  - conda-forge
  - defaults
dependencies:
  - python~=3.10.6
  - pip~=22.3
  - awscliv2~=2.1.1
  - boto3~=1.24.96
  - dask~=2023.1.1
  - fsspec~=2023.1.0
  - gdal~=3.6.2
  - geojson~=2.5.0
  - geopandas
  - hdmedians~=0.14.2
  - jsonschema~=4.17.3
  - numba~=0.56.4
  - numpy~=1.23.5
  - odc-algo~=0.2.3
  - odc-geo~=0.3.3
  - odc-stac~=0.3.5
  - pandas~=1.5.3
  - pykdtree~=1.3.6
  - pyproj~=3.4.1
  - pyresample~=1.26.0
  - pytz~=2022.7.1
  - rasterio~=1.3.4
  - requests~=2.28.2
  - rio-cogeo~=3.5.0
  - rioxarray~=0.13.3
  - scikit-learn~=1.2.1
  - scipy~=1.10.0
  - stactools~=0.4.3
  - timezonefinder~=6.1.5
  - xarray~=2023.1.0
  - zarr~=2.13.3
  - pip:
      - aiohttp~=3.8.1
      - boto3-utils~=0.3.2
      - pystac~=1.6.0
      - pystac-client~=0.4.0